## 2020_10_15

#### 可变参数

* 为什么要学可变参数（有什么用）

  观察下面代码

```java
public class VarargsTest<T> {
	public static void main(String[] args) {
		System.out.println(sum(1, 2));
		System.out.println(sum(1, 2, 3));
		System.out.println(sum(1, 2, 3, 4));
        //下面这里无法通过编译，因为sum方法最多只能接受四个参数
		System.out.println(sum(1, 2, 3, 4, 5));//error
	}

	public static int sum(int a, int b) {
		return a + b;
	}

	public static int sum(int a, int b, int c) {
		return a + b + c;
	}

	public static int sum(int a, int b, int c, int d) {
		return a + b + c + d;
	}
}
```

* 解决方法

  定义一个数组方法

```java
	//定义一个数组方法
	public static int sum(int[] args) {
		int sum = 0;
		for (int i : args) {
			sum += i;
		}
		return sum;
	}
	public static void main(String[] args) {
        //在调用时把需要计算的数据先放入数组，再传进方法里求和
		int[] i1 = {1,2,3,4,5,6,7,8,9};
		System.out.println(sum(i1));
	}
```

​		**定义一个可变参数的方法**

```java
	//我们可以传递任意数量的int类型参数，系统会自动给我们生成一个args数组
	public static int sum(int... args) {
		int sum = 0;
		for (int i : args) {
			sum += i;
		}
		return sum;
	}
	public static void main(String[] args) {
        //调用时不需要创建数组，直接传参就可以，系统会自动给我们生成一个args数组
		System.out.println(sum(1,2,3,4,5,6,7,8,9));
	}
```

* 可变参数的注意事项：

可变指的是参数个数可变

要是存在重载，系统优先使用固定参数的方法

```java
	public static String sum(int a, int b) {
		return "这里是固定参数的方法";
	}

	public static int sum(int... args) {
		int sum = 0;
		for (int i : args) {
			sum += i;
		}
		return sum;
	}
	public static void main(String[] args) {
        //既可以调用可变参数方法也可以调用固定参数方法时，优先调用固定参数方法
		System.out.println(sum(1, 2));//输出:"这里是固定参数的方法"
	}
```

可变参数**必须是最后一个参数**（只能有一个可变参数）

```java
	//存在两个可变参数时，必然会存在一个可变参数不是最后的参数
	public static int sum(int... args,int... agrs2) {//error
	}
```

----

### Java中的异常处理

#### 一，try-catch语句使用

程序运行时总是会出现各种异常如：

```java
		Scanner sc = new Scanner(System.in);
		int nextInt = sc.nextInt();
		System.out.println("异常后的代码");
```

在运行上面代码时如果在控制台输入的不是一个整数，就会出现异常如下

```java
Exception in thread "main" java.util.InputMismatchException
	at java.util.Scanner.throwFor(Unknown Source)
	at java.util.Scanner.next(Unknown Source)
	at java.util.Scanner.nextInt(Unknown Source)
	at java.util.Scanner.nextInt(Unknown Source)
	at com.yingli.exception.ExceptionTest.main(ExceptionTest.java:9)
    //为什么会出现Unkonwn Source（了解）
	因为我们直接用的是JDK直接编译好的class文件，而sun的类库在对源码进行编译的时候，没有将调试信	   息放入class文件（节省空间），所以才会显示Unknown Source。
```

可以观察到异常后的代码没有执行

**解决办法**

一，在输入前进行判断

```java
		Scanner sc = new Scanner(System.in);
		System.out.println("请输入整数");
		if (sc.hasNextInt()) {
			System.out.println("已赋值");
		} else {
			System.out.println("输入有误");
		}
```

二，**使用try-catch语句**

```java
		try {
			Scanner sc = new Scanner(System.in);
			int nextInt = sc.nextInt();
		} catch (Exception e) {
			System.out.println("程序出现异常");
		}
		System.out.println("异常后的代码");
	}
```

执行上面代码，可以观察到，异常出现后并没有影响后面代码的实现

#### 二，异常简介

异常是一种类（class），因此它存在继承关系，如下。

```ascii
                     ┌───────────┐
                     │  Object   │
                     └───────────┘
                           ▲
                           │
                     ┌───────────┐
                     │ Throwable │
                     └───────────┘
                           ▲
                 ┌─────────┴─────────┐
                 │                   │
           ┌───────────┐       ┌───────────┐
           │   Error   │       │ Exception │
           └───────────┘       └───────────┘
                 ▲                   ▲
         ┌───────┘              ┌────┴──────────┐
         │                      │               │
┌─────────────────┐    ┌─────────────────┐┌───────────┐
│OutOfMemoryError │... │RuntimeException ││IOException│...
└─────────────────┘    └─────────────────┘└───────────┘
                                ▲
                    ┌───────────┴─────────────┐
                    │                         │
         ┌─────────────────────┐ ┌─────────────────────────┐
         │NullPointerException │ │IllegalArgumentException │...
```

Exception是所有异常的父类，Exception又分两大类，RuntimeException，非RuntiimeException

Java规定：

* 必须捕获的异常：Exception类及其子类但是不包括RuntimeException及其子类（类RuntimeException）
* 不需要捕获的异常：Error及其子类，RuntimeException及其子类

#### 三，捕获异常

实际上不同的异常会产生不同的异常对象

```java
		int[] arr = new int[3];
		System.out.println(arr[3]);
```

上述程序产生的异常对象类型为：ArrayIndexOutOfBoundsException

```java
		String str = null;
		System.out.println(str.length());
```

上述程序产生的异常对象类型为：NullPointerException（其实Java里没有指针这个叫法其实继承自C）

异常还可以简单分为**必须捕捉的异常**和**非必须捕捉的异常**两种



* 必须捕捉的异常

```java
		FileOutputStream output = new FileOutputStream("C:\\Test\\Demo1.txt");
```

上面代码会抛出一个必须捕获的异常，必须对其捕捉或者抛出（否则无法通过编译）

捕捉代码如下

```java
		try {
			FileOutputStream output = new FileOutputStream("C:\\Test\\Demo1.txt");
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
```

* 非必须捕捉的异常

```java
		int[] arr = new int[3];
		System.out.println(arr[3]);
		System.out.println("异常后的程序");	
```

运行上面代码可以看到依然会抛出异常，但是编译器并没有强制让我们对异常进行捕捉

但是我们依然可以对其进行捕捉（非强制）

```java
		try {
			int[] arr = new int[3];
			System.out.println(arr[3]);
		} catch (Exception e) {
			e.printStackTrace();
		}
		System.out.println("异常后的程序");		
	}
```

运行上面代码可以看到，就算发生异常也不会影响到后续代码的执行

#### 四，发生异常时的执行顺序

* 如果没有try catch语句对异常进行及时的捕捉，程序会终止运行
* 如果有try catch语句对异常进行捕捉则会跳转到对应的catch语句中

#### 五，可以存在多个catch语句

存在多个catch语句时会从上到下区匹配符合要求的catch语句

```java
public static void Catch3() {
		try {
			int[] arr = new int[3];
			System.out.println(arr[3]);
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("这里是ArrayIndexOutOfBoundsException捕捉到的异常");
			e.printStackTrace();
		} catch(Exception e) {
			System.out.println("这里是Exception捕捉到的异常");
			e.printStackTrace();
		}
		
	}
```

**注意：**catch语句必须是子类在前父类在后，否则会报错（如果父类在前的话永远都匹配不到后面的子类）

#### 六，finally语句

有些时候一些语句我们不论什么时候都想让它执行

我们可以这样做

```java
	public static void Catch4() {
		try {
			int[] arr = new int[3];
			System.out.println(arr[3]);
			System.out.println("无论如何都想执行的语句");
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("ArrayIndexOutOfBoundsException捕捉到的异常");
			System.out.println("无论如何都想执行的语句");
			e.printStackTrace();
		} catch (Exception e) {
			System.out.println("Exception捕捉到的异常");
			System.out.println("无论如何都想执行的语句");
			e.printStackTrace();
		}
	}
```

在所有语句块后面都加上想要执行的操作，但是这样太麻烦了

这个时候我们可以用**finally语句**帮助我们简化代码

```java
	public static void Catch5() {
		try {
			int[] arr = new int[3];
			System.out.println(arr[3]);
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("ArrayIndexOutOfBoundsException捕捉到的异常");
			e.printStackTrace();
		} catch (Exception e) {
			System.out.println("Exception捕捉到的异常");
			e.printStackTrace();
		}finally {
			System.out.println("无论如何都想执行的语句");
		}
	}
```

#### 七，在catch中使用 | （或）运算符

如果要捕捉的两个异常类型间不存在继承关系,且执行操作一样时，如

```java
	public static void Catch6() {
		try {
			int[] arr = new int[3];
			System.out.println(arr[3]);
		} catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("捕捉到的异常");
			e.printStackTrace();
		} catch (NullPointerException e) {
			System.out.println("捕捉到的异常");
			e.printStackTrace();
	}
```

这个时候可以使用|（或）运算符简化代码

```java
	public static void Catch7() {
		try {
			int[] arr = new int[3];
			System.out.println(arr[3]);
		} catch (ArrayIndexOutOfBoundsException|NullPointerException e) {
			System.out.println("捕捉到的异常");
			e.printStackTrace();
		}
	}
```



#### 七，异常的传播

**throw**关键字

throw写在方法体中，在特定情况时把异常抛出

```java
public class ThrowTest {
	public static void main(String[] args) {
		method1();
	}

	public static void method1() {
		method2();
	}

	public static void method2() {
		throw new NullPointerException();
	}
}
```

**throws**关键字

throws写在方法名的括号后，意思是将异常往上抛出，谁调用这个方法，谁就去处理异常（当然，调用方法者也可以将异常继续throws往外抛出）

```java
public class ThrowTest1 {
	public static void main(String[] args) {
		try {
			method1();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public static void method1() throws IOException {
		method2();
	}

	public static void method2() throws IOException {
		throw new IOException();
	}
}
```

相比throw和throws这两个甩手掌柜而言，try...catch就是那个辛苦劳作的人，负责对异常进行最后的真正的处理。

**注意：对于必须捕捉的异常，要么用try catch语句捕捉异常，要么抛出**

------

### JUnit单元测试

#### 一，为什么要用JUnit

方便我们对方法进行测试，之前我们想要测试一个方法是否能正常运行时需要先将对象实例化出来，再让对象去调用方法，如下

```java
public class Test {
	public static void main(String[] args) {
		Test t = new Test();
		t.show();
	}

	public void show() {
		System.out.println("这里是一个show方法");
	}
	

	public void show2() {
		System.out.println("这里是一个show2方法");
	}
}
```

#### JUnit的优点

使用它可以单独去运行某个方法

可以将你的程序划分为很多小块，任意测试

#### JUnit的使用

使用Junit的步骤

1、在工程中引入Junit的Jar包

> 对工程右键-----build path ----add  libraries -----选择Junit  ----点击next -----版本5--- finish

2、在需要测试的方法上写标签@Test，选择org.junit.Test

3、代码中鼠标右键-----run as-----junit test  

```java
public class JUnitTest {
	
	@Test
	public void show() {
		System.out.println("这里是一个show方法");
	}
	
	public void show2() {
		System.out.println("这里是一个show2方法");
	}
}
```